"""
pypylon - Python wrapper for Basler pylon Camera Software Suite

This package provides Python bindings for the Basler pylon SDK, enabling
control of Basler cameras from Python applications.
"""

# Import version information (generated by setuptools_scm)
try:
    from ._version import __version__
except ImportError:
    # Fallback if _version.py is not available (e.g., development install)
    try:
        from importlib.metadata import version
        __version__ = version("pypylon")
    except ImportError:
        __version__ = "unknown"

# Import the main modules (SWIG-generated Python interface files)
try:
    from . import genicam
    from . import pylon
    
    # Import data processing if available
    try:
        from . import pylondataprocessing
        HAS_DATA_PROCESSING = True
    except ImportError:
        HAS_DATA_PROCESSING = False
        pylondataprocessing = None
        
except ImportError as e:
    # This can happen if the extensions haven't been built yet
    import warnings
    warnings.warn(f"Could not import pypylon extensions: {e}")
    genicam = None
    pylon = None
    pylondataprocessing = None
    HAS_DATA_PROCESSING = False

# Re-export commonly used items for convenience
__all__ = [
    '__version__',
    'genicam', 
    'pylon',
    'pylondataprocessing',
    'HAS_DATA_PROCESSING'
] 